name: my-manim-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9  # Adjust version if needed
  - pip:
    - manim==0.17.1  # Update to a compatible version of Manim
    - numpy
    - matplotlib
